services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_NAME=note_app
      - DB_USER=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - notes_network
    extra_hosts:
    - "host.docker.internal:host-gateway"

  db:
    image: mysql
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=note_app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - notes_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - notes_network

networks:
  notes_network:
    driver: bridge

volumes:
  db:
   driver: local
